version: '2'

services:

  web:
    build:
      context: .
      args:
        APP_ENV: production
    image: inftxos:0.2.86
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENSTATES_API_KEY=${OPENSTATES_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_ANALYTICS=${GOOGLE_ANALYTICS}
    network_mode: "host"
    ports:
      - "5120:5120"

  redis:
    image: redis:alpine
    container_name: redis
    network_mode: "host"
    ports:
      - "6379:6379"
